version: '3.7'

services:
  spotifyinfo:
    container_name: spotifyinfo
    hostname: spotifyinfo
    build: .
    user: 65534:65534
    read_only: true
    restart: always
    ports:
      - '127.0.0.1:3014:3000'
    environment:
      - "NEXT_PUBLIC_HOST_URL=http://localhost:3014"
      - "NEXT_PUBLIC_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
# use if you get the error: ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
#sudo docker network create "spotifyinfo" --subnet="172.16.0.0/16"
#networks:
  #default:
    #external:
      #name: spotifyinfo
